language: php
sudo: false

php:
  - 7.0
  - 5.6
  - 5.5
  - 5.4
  - 5.3

env:
  - DB=sqlite
  - DB=mysql
  - DB=postgres

matrix:
  fast_finish: true

before_script:
  - phpenv config-add tests/php.ini
  - composer install
  - wget https://phar.phpunit.de/phpunit.phar

script:
  - php phpunit.phar -c tests/units.$DB.xml